'use client'
import './globals.css'
import {Inter} from 'next/font/google'
import React from "react";

const inter = Inter({subsets: ['latin']})

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
              crossOrigin="anonymous"></link>
        {/*<C_menuComponent></C_menuComponent>*/}
        {children}
        <footer style={{
            textAlign: "center",
            color: "white",
            backgroundColor: "#401264"
        }}>
            <div>
                <h4>
                    NICKELODEON LATINOAMERICA
                </h4>
            </div>
            <div>
                <p>
                    ¡Diviértete en nuestro sitio oficial con lo mejor de tus series favoritas de Nick!
                </p>
            </div>
            <div>
                <div>
                    <ul>
                        <li>
                            <a>POLITICA DE PRIVACIDAD</a>
                        </li>
                        <li>
                            <a>TERMINCOS Y CONDICIONES</a>
                        </li>
                    </ul>
                </div>
                <div>
                    <ul>
                        <li><i></i></li>
                        <li><i></i></li>
                        <li><i></i></li>
                        <li><i></i></li>
                    </ul>
                </div>
                <div>
                    <p>
                        © Viacom International Media Networks 2023
                    </p>
                </div>
            </div>
        </footer>
        </body>
        </html>
    )
}
